# Generated by Django 4.1.7 on 2023-03-22 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('location', models.IntegerField(blank=True, db_column='Location', null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=20, null=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'edition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InputTable',
            fields=[
                ('location', models.CharField(blank=True, db_column='Location', max_length=200, null=True)),
                ('theater_name', models.CharField(blank=True, db_column='Theater_name', max_length=200, null=True)),
                ('film_name', models.CharField(blank=True, db_column='Film_name', max_length=200, null=True)),
                ('language', models.CharField(blank=True, db_column='Language', max_length=200, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('show_time', models.CharField(blank=True, db_column='Show_time', max_length=200, null=True)),
                ('place', models.CharField(blank=True, max_length=300, null=True)),
                ('screen', models.CharField(blank=True, max_length=200, null=True)),
                ('t_sub', models.CharField(blank=True, db_column='T_sub', max_length=200, null=True)),
                ('contact_no', models.CharField(blank=True, db_column='Contact_no', max_length=300, null=True)),
                ('booking', models.CharField(blank=True, db_column='Booking', max_length=300, null=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('no_show', models.CharField(blank=True, db_column='No_Show', max_length=45, null=True)),
                ('oldtheatername', models.CharField(blank=True, db_column='OldTheaterName', max_length=150, null=True)),
            ],
            options={
                'db_table': 'input_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Spread',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dashboard.edition')),
                ('location', models.IntegerField(blank=True, null=True)),
                ('edt_id', models.IntegerField(db_column='Edt_id')),
                ('theater', models.CharField(blank=True, db_column='Theater', max_length=100, null=True)),
                ('spread', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'spread',
                'managed': False,
            },
        ),
    ]
