# Generated by Django 4.1.7 on 2023-03-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editionplaces',
            fields=[
                ('priority', models.IntegerField(blank=True, db_column='Priority', null=True, unique=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'editionplaces',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=100)),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('location', models.IntegerField(blank=True, db_column='Location', null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=250, null=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'places',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('contactnumber', models.CharField(db_column='ContactNumber', max_length=100)),
                ('screen', models.CharField(db_column='Screen', max_length=100)),
                ('t_sub', models.CharField(blank=True, db_column='T_sub', max_length=100, null=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('priority', models.IntegerField(db_column='Priority')),
                ('booking', models.TextField(blank=True, db_column='Booking', max_length=100, null=True)),
                ('oldtheatername', models.CharField(blank=True, db_column='OldTheaterName', max_length=150, null=True)),
            ],
            options={
                'db_table': 'theaters',
                'managed': False,
            },
        ),
    ]
