# Generated by Django 4.1.7 on 2023-04-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_editionplaces_location_places_theater'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyInputs',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('film_name', models.CharField(db_column='film_name', max_length=200)),
                ('language', models.CharField(db_column='language', max_length=200)),
                ('current', models.BooleanField(db_column='current', default='False')),
                ('show_times', models.CharField(db_column='show_times', max_length=200)),
                ('date', models.DateField(db_column='date')),
            ],
            options={
                'db_table': 'dailyinputs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=45)),
                ('place', models.CharField(db_column='Place', max_length=45)),
                ('screen_no', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'screen',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'managed': False, 'permissions': [('editALP', 'Can edit location Alappuzha'), ('editCLT', 'Can edit location Calicut'), ('editCHN', 'Can edit location Cochin'), ('editKNR', 'Can edit location Kannur'), ('editQLN', 'Can edit location Kollam'), ('editKTM', 'Can edit location Kottayam'), ('editMPM', 'Can edit location Malappuram'), ('editPKD', 'Can edit location Palakkad'), ('editPTA', 'Can edit location Pathanamthitta'), ('editTCR', 'Can edit location Thrissur'), ('editTVM', 'Can edit location Trivandrum')]},
        ),
    ]
